name: Clone from Azure DevOps and Push to GitHub

on:
  workflow_dispatch:  # Hiermee kun je de workflow handmatig starten

jobs:
  clone-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Clone Azure DevOps repository
        env:
          AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
        run: |
          git clone https://defoortd:${{ secrets.AZURE_DEVOPS_PAT }}@dev.azure.com/defoortd/bachelorproef%20Emre/_git/bachelorproef%20Emre bpPoc

      - name: Push to GitHub repository
        env:
          GITHUB_PAT: ${{ secrets.ADMIN_PAT }}
        run: |
          cd bpPoc
          git remote add github https://github.com/Emre-Igten/bpPOC.git
          git push https://x-access-token:${{ secrets.ADMIN_PAT }}@github.com/Emre-Igten/bpPOC.git main

    #   - name: Set up Terraform
    #     uses: hashicorp/setup-terraform@v1

    #   - name: Terraform Init
    #     run: terraform init


    #   - name: Terraform Plan - Create Team and Repository
    #     run: |
    #       terraform plan -out=tfplan2 -target="
  
  
    #   - name: Terraform Apply - Create Team and Repository
    #     run: |
    #       terraform apply "tfplan2"
  