name: Clone, Push, and Apply Terraform

on:
  workflow_dispatch: # Manueel te starten

jobs:
  clone-push-and-terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Clone Azure DevOps repository
        run: |
          cd C:\Users\Gebruiker\Desktop\SCHOOL\S2
          git clone https://defoortd@dev.azure.com/defoortd/bachelorproef%20Emre/_git/bachelorproef%20Emre
      
      - name: Push to GitHub repository
        run: |      
          cd C:\Users\Gebruiker\Desktop\SCHOOL\S2
          git remote add github https://github.com/Emre-Igten/bpPOC.git
          git push github master

    #   - name: Set up Terraform
    #     uses: hashicorp/setup-terraform@v1

    #   - name: Terraform Init
    #     run: terraform init


    #   - name: Terraform Plan - Create Team and Repository
    #     run: |
    #       terraform plan -out=tfplan2 -target="
  
  
    #   - name: Terraform Apply - Create Team and Repository
    #     run: |
    #       terraform apply "tfplan2"
  