name: Create Organization

on: 
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4


    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0


    # The secret should be the one you added to your repository (Should be a PAT with admin permissions)
    - name: Set GitHub Token
      run: echo "GITHUB_TOKEN=${{ secrets.ADMIN_TOKEN2 }}" >> $GITHUB_ENV



    - name: Terraform Init
      run: terraform init


    # Has to run before the other modules
    - name: Terraform Plan
      run: terraform plan -out=tfplan -target="module.create-organization"


    - name: Terraform Apply
      run: terraform apply "tfplan"